manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: badjeff
    url-base: https://github.com/badjeff
  - name: carrefinho
    url-base: https://github.com/carrefinho
  - name: englmaxi
    url-base: https://github.com/englmaxi
  # janpfischer remote disabled - zmk-dongle-screen has Zephyr 4.1 compatibility issues
  # - name: janpfischer
  #   url-base: https://github.com/janpfischer
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: zmk-pmw3610-driver
    remote: badjeff
    revision: zmk-0.4
  - name: prospector-zmk-module
    remote: carrefinho
    revision: core/zephyr-4-1
  - name: zmk-dongle-display
    remote: englmaxi
    revision: main
  # zmk-dongle-screen disabled - Zephyr 4.1 compatibility issues pending upstream fix
  # See: https://github.com/janpfischer/zmk-dongle-screen/issues/29
  # - name: zmk-dongle-screen
  #   remote: janpfischer
  #   revision: upgrade-4.1
  self:
    path: config
